# Take Home exercise 2

In [1]:
import numpy as np
import pandas as pd

In [3]:
dataset_path = './data/question_3.data'
dataset_df = pd.read_csv(dataset_path)
dataset_df

  known-bugs  profit delay decision
0       high    high  high  release
1     medium    high   low  release
2     medium     low   low     wait
3       high  medium   low     wait
4       high     low  high     wait
5        low     low   low     wait
6       high    high   low     wait
7        low     low  high  release
8     medium  medium  high     wait
9     medium    high  high  release

# Preprocessing

In [18]:
from sklearn.model_selection import train_test_split

y = pd.DataFrame(dataset_df['decision'])
X = dataset_df.drop(['decision'], axis=1)

X_train, X_test, y_train, y_test = train_test_split(X, y, train_size=0.7, test_size=0.3, random_state=25)
X_train

  known-bugs  profit delay
8     medium  medium  high
0       high    high  high
2     medium     low   low
9     medium    high  high
7        low     low  high
6       high    high   low
4       high     low  high

In [20]:
s = (X_train.dtypes == 'object')
object_cols = list(s[s].index)

print("Categorical variables:")
print(object_cols)
print(len(object_cols))
# LOL!! all of them are object types!

Categorical variables:
['known-bugs', 'profit', 'delay']
3

In [26]:
from sklearn.preprocessing import LabelEncoder

# Make copy to avoid changing original data 
label_X_train = X_train.copy()
label_X_test = X_test.copy()

label_y_train = y_train.copy()
label_y_test = y_test.copy()

# Apply label encoder to each column with categorical data
label_encoder = LabelEncoder()
for col in object_cols:
    label_X_train[col] = label_encoder.fit_transform(X_train[col])
    label_X_test[col] = label_encoder.transform(X_test[col])

X_train = label_X_train
X_test = label_X_test    

for col in y_train.columns:
    label_y_train[col] = label_encoder.fit_transform(y_train[col])
    label_y_test[col] = label_encoder.transform(y_test[col])
    
y_train = label_y_train
y_test = label_y_test

X_train

   known-bugs  profit  delay
8           2       2      0
0           0       0      0
2           2       1      1
9           2       0      0
7           1       1      0
6           0       0      1
4           0       1      0

In [27]:
y_train

   decision
8         1
0         0
2         1
9         0
7         0
6         1
4         1

# I Could write the whole program but it's 22:45 O'clock and I don't have any time left. so sorry :(